coef_1 = 1
coef_2 = 2
coef_3 = 3
ago_dev = float(input("Note agora devoir: "))
ago_exam = float(input("Note agora exam: "))
algo_dev = float(input("Note algo devoir: "))
algo_exam = float(input("Note algo exam: "))
eng_dev = float(input("Note anglais devoir: "))
eng_exam = float(input("Note anglais exam: "))
cms_dev = float(input("Note wordpress devoir: "))
cms_exam = float(input("Note wordpress exam: "))
cg_dev = float(input("Note conception graphique devoir: "))
cg_exam = float(input("Note conception graphique  exam: "))
eco_dev = float(input("Note economie d'entreprise devoir: "))
eco_exam = float(input("Note economie d'entreprise exam: "))
elec_exam = float(input("Note electricite exam: "))
math_dev = float(input("Note maths devoir: "))
math_exam = float(input("Note maths exam: "))
python_dev = float(input("Note python devoir: "))
python_exam = float(input("Note python exam: "))
ccna_dev = float(input("Note ccna exam: "))
ccna_exam = float(input("Note ccna exam: "))
html_dev = float(input("Note html devoir: "))
html_exam = float(input("Note html exam: "))
agora = (ago_dev * 0.4 + ago_exam * 0.6) * coef_3
english = (eng_dev * 0.4 + eng_exam * 0.6) * coef_1
algo = (algo_dev * 0.4 + algo_exam * 0.6) * coef_2
cms = (cms_dev * 0.4 + cms_exam * 0.6) * coef_2
cg = (cg_dev * 0.4 + cg_exam * 0.6) * coef_1
eco = (eco_dev * 0.4 + eco_exam * 0.6) * coef_2
electricite = (elec_exam * 0.6) * coef_2
maths = (math_dev * 0.4 + math_exam * 0.6) * coef_2
python = (python_dev * 0.4 + python_exam * 0.6) * coef_2
ccna = (ccna_dev * 0.4 + ccna_exam * 0.6) * coef_2
html= (html_dev * 0.4 + html_exam * 0.6) * coef_2
moyenne = algo + english + cms + cg + eco + electricite + maths + python + ccna + html + agora
print("Resultat: \n ") 
print(f"moyenne: {moyenne}; {moyenne / 18}")
